name: scheduled_run

# контарлирует события по которым запускается пайп-лайн спусковой крючек ПЛ
on:
  workflow: dispatch
  schedule:
    - cron: 30 3 * * 4
# добовляем возможность запуска с кнопки
jobs:
  
  build:
    # конфигурация
    runs-on: ubuntu-latest

    # шаги которые мы выполням для выполнения задачи
    steps:
      # первый шаг. притягиваем код с удаленного репозитория
      - name: Pulls code from remote repository
        uses: actions/checkout@v4

      # устаноыкв node.js
      - name: install Node.js
        uses: actions/setup-node@v4

      # установка newman
      - name: install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      # запуск теста с формированиме отчета    
      - name: test run
        run: newman run Trello_Roman.postman_collection.json -e Trello_Environment.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export Report.html   
